"""initial schema (Phase 1)

워크스페이스·소스·수집 작업·콘텐츠. 첫 줄은 alembic 이 콘솔에 찍으므로 ASCII 로 둔다.
타입은 범용 SQLAlchemy 타입으로 적는다 (env.py render_item). 앱 코드를 import 하지 않는다.

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 17:25:44.631032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.String(length=5), nullable=True),
    sa.Column('cron_expr', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_body_length', sa.Integer(), nullable=False),
    sa.Column('allow_non_korean', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sources_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('collection_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('collected_count', sa.Integer(), nullable=False),
    sa.Column('stage_counts', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_collection_jobs_source_id_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_collection_jobs_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_jobs'))
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source_keywords',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_keywords_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_keywords_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_keywords')),
    sa.UniqueConstraint('source_id', 'keyword', name='uq_source_keywords_source_id_keyword')
    )
    with op.batch_alter_table('source_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_keywords_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_keywords_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('contents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('first_job_id', sa.Integer(), nullable=False),
    sa.Column('collection_path', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('board_url', sa.Text(), nullable=False),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('cleaned_body', sa.Text(), nullable=False),
    sa.Column('body_length', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_job_id'], ['collection_jobs.id'], name=op.f('fk_contents_first_job_id_collection_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_contents_source_id_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contents_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contents')),
    sa.UniqueConstraint('workspace_id', 'url_hash', name='uq_contents_workspace_id_url_hash')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_contents_workspace_id_collected_at', ['workspace_id', 'collected_at'], unique=False)
        batch_op.create_index('ix_contents_workspace_id_published_at', ['workspace_id', 'published_at'], unique=False)
        batch_op.create_index('ix_contents_workspace_id_source_id', ['workspace_id', 'source_id'], unique=False)

    op.create_table('job_api_responses',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['collection_jobs.id'], name=op.f('fk_job_api_responses_job_id_collection_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_job_api_responses_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_api_responses'))
    )
    with op.batch_alter_table('job_api_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_api_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_api_responses_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_api_responses_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('content_keyword_hits',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('source_keyword_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_content_keyword_hits_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['collection_jobs.id'], name=op.f('fk_content_keyword_hits_job_id_collection_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_keyword_id'], ['source_keywords.id'], name=op.f('fk_content_keyword_hits_source_keyword_id_source_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_keyword_hits_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_keyword_hits')),
    sa.UniqueConstraint('content_id', 'keyword', name='uq_content_keyword_hits_content_id_keyword')
    )
    with op.batch_alter_table('content_keyword_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_keyword_hits_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_keyword_hits_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_keyword_hits_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_keyword_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_keyword_hits_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_content_keyword_hits_job_id'))
        batch_op.drop_index(batch_op.f('ix_content_keyword_hits_content_id'))

    op.drop_table('content_keyword_hits')
    with op.batch_alter_table('job_api_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_api_responses_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_job_api_responses_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_api_responses_created_at'))

    op.drop_table('job_api_responses')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_workspace_id_source_id')
        batch_op.drop_index('ix_contents_workspace_id_published_at')
        batch_op.drop_index('ix_contents_workspace_id_collected_at')
        batch_op.drop_index(batch_op.f('ix_contents_workspace_id'))

    op.drop_table('contents')
    with op.batch_alter_table('source_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_keywords_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_source_keywords_source_id'))

    op.drop_table('source_keywords')
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_collection_jobs_source_id'))

    op.drop_table('collection_jobs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_sources_next_run_at'))

    op.drop_table('sources')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
